# Development environment for anglerfish
name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::minimap2=2.26
  - pip
  - pip:
      - -r requirements.txt
  - conda-forge::pre-commit
  - conda-forge::prettier
