name: anglerfish
channels:
  - bioconda
  - conda-forge
dependencies:
  - conda-forge::biopython=1.70
  - conda-forge::python-levenshtein=0.12.0
  - bioconda::minimap2=2.17
  - bioconda::fastqc=0.11.9
  - bioconda::busco=3.0.2
  - bioconda::quast=5.0.2
  - bioconda::multiqc=1.8
