name: anglerfish
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::biopython=1.79
  - conda-forge::python-levenshtein=0.12.1
  - conda-forge::numpy=1.22.0
  - bioconda::minimap2=2.20
  - conda-forge::pyyaml=6.0
