name: anglerfish
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::biopython=1.79
  - conda-forge::python-levenshtein=0.20.5
  - conda-forge::numpy=1.22.0
  - bioconda::minimap2=2.20
