# More adaptors can be added manually, following the format below.
# The position of an index within an adaptor is represented by the delimiter "<N>".
# The position and length of the UMI within an adaptor is represented by the delimiter "<U#>" where # is the length of the UMI.
# The indexes themselves are represented in the sample sheet.

# Ilumina unique dual indexes, see https://web.archive.org/web/20231129095351/https://support-docs.illumina.com/SHARE/AdapterSequences/Content/SHARE/AdapterSeq/Illumina_DNA/IlluminaUDIndexes.htm
illumina_ud:
  i5: AATGATACGGCGACCACCGAGATCTACAC<N>TCGTCGGCAGCGTC
  i7: CAAGCAGAAGACGGCATACGAGAT<N>GTCTCGTGGGCTCGG

truseq:
  i5: AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT
  i7: GATCGGAAGAGCACACGTCTGAACTCCAGTCAC<N>ATCTCGTATGCCGTCTTCTGCTTG

truseq_dual:
  i5: AATGATACGGCGACCACCGAGATCTACAC<N>ACACTCTTTCCCTACACGACGCTCTTCCGATCT
  i7: GATCGGAAGAGCACACGTCTGAACTCCAGTCAC<N>ATCTCGTATGCCGTCTTCTGCTTG

truseq_umi:
  i5: AATGATACGGCGACCACCGAGATCTACAC<N>ACACTCTTTCCCTACACGACGCTCTTCCGATCT
  i7: GATCGGAAGAGCACACGTCTGAACTCCAGTCAC<N><U9>ATCTCGTATGCCGTCTTCTGCTTG

nextera_legacy:
  i5: AATGATACGGCGACCACCGAGATCTACACGCCTCCCTCGCGCCATCAG
  i7: CAAGCAGAAGACGGCATACGAGAT<N>CGGTCTGCCTTGCCAGCCCGCTCAG

nextera_dual:
  i5: AATGATACGGCGACCACCGAGATCTACAC<N>GTCTCGTGGGCTCGG
  i7: CAAGCAGAAGACGGCATACGAGAT<N>ATCTCGTATGCCGTCTTCTGCTTG
