name: Anglerfish
on: [push, pull_request]

jobs:
  run_anglerfish:
    name: Anglerfish py-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      # Checkout code and install miniconda + environment
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: anglerfish
           environment-file: environment.yml
           python-version: ${{ matrix.python-version }}
           auto-activate-base: false

      # Install Anglerfish
      - shell: bash -l {0}
        name: Install Anglerfish
        run: python setup.py install

      # Run anglerfish.py --help
      - shell: bash -l {0}
        name: Test anglerfish.py
        run: anglerfish.py --help

      # Run anglerfish using test data
      - shell: bash -l {0}
        name: Run anglerfish.py with test data
        run: anglerfish.py -s test/samples.csv
