name: Anglerfish
on: [push, pull_request]

jobs:
  run_anglerfish:
    name: Anglerfish py-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v1
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: anaconda-client-env
           environment-file: environment.yml
           python-version: ${{ matrix.python-version }}
           auto-activate-base: false

      - name: Install Anglerfish
        run: python setup.py install

      - name: Test anglerfish.py
        run: anglerfish.py --help
