name: Anglerfish
on: [push, pull_request]

jobs:
  run_anglerfish:
    name: Anglerfish py-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.2]

    steps:
      # Checkout code and install miniconda + environment
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }}
            pip
          environment-file: environment.yml
          environment-name: anglerfish-dev

      # Install Anglerfish
      - shell: bash -l {0}
        name: Install Anglerfish
        run: |
          python -m pip install .

      # Run anglerfish --help
      - shell: bash -l {0}
        name: Test anglerfish
        run: |
          anglerfish --help

      # Run anglerfish using test data
      - shell: bash -l {0}
        name: Run anglerfish with test data
        run: |
          anglerfish run -s testdata/samples.csv

      # Run anglerfish explore
      - shell: bash -l {0}
        name: Run anglerfish explore
        run: |
          anglerfish explore -f testdata/BC18_P14351_1001.fastq.gz -o explore_output
