name: Publish anglerfish to PyPI
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out source-code repository

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          pip install .
      - name: Build the distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish anglerfish to PyPI
        if: github.repository == 'NationalGenomicsInfrastructure/anglerfish'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
