name: test-code
on: [push, pull_request]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      # Checkout code and install miniconda + environment
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }}
            pip
          environment-file: environment.yml
          environment-name: anglerfish-dev

      # Install Anglerfish
      - shell: bash -l {0}
        name: Install Anglerfish
        run: |
          python -m pip install .

      # Install Pytest
      - shell: bash -l {0}
        name: Install Pytest
        run: |
          python -m pip install pytest

      # Run Pytest
      - shell: bash -l {0}
        name: Run Pytest
        run: |
          pytest .
